### ISSUE TITLE
gulp-micro already exists

### ISSUE THREAD

**Issue by anissen** [adriancooney/gulp-js1k#1]
Just a heads-up; there is already a gulp-plug-in for warning when a certain file size is exceeded: https://github.com/sindresorhus/gulp-micro

One valuable addition to your library could be to use google closure compiler, uglify and then jscrush (http://www.iteral.com/jscrush/) to crush every last byte out of the code :)

**Comment by adriancooney** [comment]
Yeah, I quickly tossed this together. I really have to refine the code and modules. Thanks for the tips, I'll take a look at integrating them.
